#include "lang.h"

namespace {
const std::unordered_map<std::string, std::string> RU = {
    {"title", "VirusTotal Scanner Pro"},
    {"select_file", "Выбрать файл"},
    {"scanning", "Сканирование..."},
    {"ready", "Готов к работе"},
    {"no_file", "Файл не выбран"},
    {"file_info", "Информация о файле"},
    {"actions", "Действия"},
    {"status", "Статус"},
    {"results", "Результаты сканирования"},
    {"clear", "Очистить"},
    {"about", "О программе"},
    {"change_api_key", "Сменить API ключ"},
    {"settings", "Настройки"},
    {"copy_hash", "Копировать хеш"},
    {"open_in_browser", "Открыть на VirusTotal"},
    {"size", "Размер"},
    {"sha256", "SHA-256"},
    {"api_key_dialog_title", "Настройка API ключа"},
    {"api_key_dialog_text", "Введите ваш API ключ VirusTotal:"},
    {"api_key_warning", "API ключ не введен. Программа будет работать некорректно!"},
    {"api_key_updated", "API ключ успешно обновлен!"},
    {"hash_copied", "Хеш скопирован!"},
    {"hash_not_found", "Хеш не найден"},
    {"output_cleared", "Вывод очищен"},
    {"hash_calc", "Вычисление SHA-256..."},
    {"checking_db", "Проверка в базе VirusTotal..."},
    {"file_not_in_db", "Файл не найден в базе. Загрузка..."},
    {"uploading", "Загрузка файла на сервер..."},
    {"file_uploaded", "Файл загружен!"},
    {"file_found_in_db", "Файл найден в базе!"},
    {"ready_report_from_db", "Готовый отчет из базы!"},
    {"waiting_scan", "Ожидание проверки антивирусами..."},
    {"waiting_scan_text", "Ожидание проверки (до 7 минут)..."},
    {"scan_complete", "Проверка завершена!"},
    {"timeout_warning", "Время ожидания истекло"},
    {"check_later", "Проверьте позже"},
    {"error_network", "Нет подключения к интернету!"},
    {"error_timeout", "Превышено время ожидания!"},
    {"error_fail", "Сбой"},
    {"no_detections", "ЧИСТО! Ни один антивирус не нашел угроз."},
    {"threats_detected", "ОБНАРУЖЕНЫ УГРОЗЫ"},
    {"total_detections", "Всего обнаружений"},
    {"full_report", "Полный отчет"},
    {"comments", "КОММЕНТАРИИ"},
    {"no_comments", "Комментариев нет"},
    {"stats", "СТАТИСТИКА"},
    {"harmless", "Безопасные"},
    {"undetected", "Не обнаружено"},
    {"suspicious", "Подозрительные"},
    {"malicious", "Вредоносные"},
    {"timeout_stats", "Таймаут"},
    {"reputation", "РЕЙТИНГ СООБЩЕСТВА"},
    {"votes_for", "За"},
    {"votes_against", "Против"},
    {"theme", "Тема"},
    {"dark", "Тёмная"},
    {"light", "Светлая"},
    {"sound", "Звук при завершении сканирования"},
    {"api_type", "Тип API ключа"},
    {"free", "Бесплатный"},
    {"paid", "Платный"},
    {"save", "Сохранить"},
    {"ok", "ОК"},
    {"cancel", "Отмена"},
    {"about_program", "О программе"},
    {"language", "Язык"},
    {"lang_ru", "Русский"},
    {"lang_en", "English"},
    {"topmost", "Поверх других окон"},
    {"requests_used", "Потрачено"},
    {"warning_title", "Предупреждение"},
    {"kb", "КБ"},
    {"bytes_unit", "байт"},
    {"date_label", "Дата"},
    {"file_label", "Файл"},
    {"method_label", "Метод"},
    {"unknown_object", "Подозрительный объект"},
    {"scan_start_header", "НАЧАЛО СКАНИРОВАНИЯ"},
    {"scan_start_note1", "Это может занять до 5 минут..."},
    {"scan_start_note2", "Пожалуйста, подождите."},
    {"check_now", "Проверить сейчас"},
    {"success", "Успех"},
    {"scan_results_header", "РЕЗУЛЬТАТЫ СКАНИРОВАНИЯ"},
    {"anonymous", "Аноним"},
    {"rescan", "Пересканировать"},
    {"zenity_missing", "Диалог выбора файла не найден. Установите: sudo apt install zenity"},
    {"about_text",
        "VirusTotal Scanner Pro (C++ / Dear ImGui + OpenGL + X11)\n\n"
        "Логика работы:\n"
        "1. Проверяет SHA-256 хеш файла\n"
        "2. Если файл есть в базе - показывает готовый отчет\n"
        "3. Если нет - загружает и ждет результат\n\n"
        "Требуется бесплатный или платный API ключ VirusTotal.\n"
        "Получить ключ: https://www.virustotal.com/gui/join-us"},
};

const std::unordered_map<std::string, std::string> EN = {
    {"title", "VirusTotal Scanner Pro"},
    {"select_file", "Select file"},
    {"scanning", "Scanning..."},
    {"ready", "Ready"},
    {"no_file", "No file selected"},
    {"file_info", "File info"},
    {"actions", "Actions"},
    {"status", "Status"},
    {"results", "Scan results"},
    {"clear", "Clear"},
    {"about", "About"},
    {"change_api_key", "Change API key"},
    {"settings", "Settings"},
    {"copy_hash", "Copy hash"},
    {"open_in_browser", "Open on VirusTotal"},
    {"size", "Size"},
    {"sha256", "SHA-256"},
    {"api_key_dialog_title", "Setup API key"},
    {"api_key_dialog_text", "Enter your VirusTotal API key:"},
    {"api_key_warning", "API key not entered. The program will not work correctly!"},
    {"api_key_updated", "API key updated successfully!"},
    {"hash_copied", "Hash copied!"},
    {"hash_not_found", "Hash not found"},
    {"output_cleared", "Output cleared"},
    {"hash_calc", "Calculating SHA-256..."},
    {"checking_db", "Checking VirusTotal database..."},
    {"file_not_in_db", "File not found in database. Uploading..."},
    {"uploading", "Uploading file to server..."},
    {"file_uploaded", "File uploaded!"},
    {"file_found_in_db", "File found in database!"},
    {"ready_report_from_db", "Ready report from database!"},
    {"waiting_scan", "Waiting for antivirus check..."},
    {"waiting_scan_text", "Waiting for check (up to 7 minutes)..."},
    {"scan_complete", "Scan complete!"},
    {"timeout_warning", "Waiting time expired"},
    {"check_later", "Check later"},
    {"error_network", "No internet connection!"},
    {"error_timeout", "Timeout exceeded!"},
    {"error_fail", "Fail"},
    {"no_detections", "CLEAN! No antivirus detected any threats."},
    {"threats_detected", "THREATS DETECTED"},
    {"total_detections", "Total detections"},
    {"full_report", "Full report"},
    {"comments", "COMMENTS"},
    {"no_comments", "No comments"},
    {"stats", "STATISTICS"},
    {"harmless", "Harmless"},
    {"undetected", "Undetected"},
    {"suspicious", "Suspicious"},
    {"malicious", "Malicious"},
    {"timeout_stats", "Timeout"},
    {"reputation", "COMMUNITY REPUTATION"},
    {"votes_for", "For"},
    {"votes_against", "Against"},
    {"theme", "Theme"},
    {"dark", "Dark"},
    {"light", "Light"},
    {"sound", "Sound on scan complete"},
    {"api_type", "API key type"},
    {"free", "Free"},
    {"paid", "Paid"},
    {"save", "Save"},
    {"ok", "OK"},
    {"cancel", "Cancel"},
    {"about_program", "About"},
    {"language", "Language"},
    {"lang_ru", "Русский"},
    {"lang_en", "English"},
    {"topmost", "Always on top"},
    {"requests_used", "Used"},
    {"warning_title", "Warning"},
    {"kb", "KB"},
    {"bytes_unit", "bytes"},
    {"date_label", "Date"},
    {"file_label", "File"},
    {"method_label", "Method"},
    {"unknown_object", "Suspicious object"},
    {"scan_start_header", "SCAN STARTED"},
    {"scan_start_note1", "This may take up to 5 minutes..."},
    {"scan_start_note2", "Please wait."},
    {"check_now", "Check now"},
    {"success", "Success"},
    {"scan_results_header", "SCAN RESULTS"},
    {"anonymous", "Anonymous"},
    {"rescan", "Rescan"},
    {"zenity_missing", "File dialog not found. Install it: sudo apt install zenity"},
    {"about_text",
        "VirusTotal Scanner Pro (C++ / Dear ImGui + OpenGL + X11)\n\n"
        "Logic:\n"
        "1. Checks SHA-256 hash of the file\n"
        "2. If the file is in the database - shows a ready report\n"
        "3. If not - uploads and waits for the result\n\n"
        "Requires a free or paid VirusTotal API key.\n"
        "Get a key: https://www.virustotal.com/gui/join-us"},
};
}

std::string T(Lang lang, const std::string& key) {
    const auto& map = (lang == Lang::EN) ? EN : RU;
    auto it = map.find(key);
    if (it != map.end()) return it->second;
    if (lang == Lang::EN) {
        auto ru = RU.find(key);
        if (ru != RU.end()) return ru->second;
    }
    return key;
}